#!/usr/bin/env bash
set -o pipefail
set -e

INPUT=$1
CHROMSIZE=$2
OUTDIR=$3
OUTPREFIX=$4
WINSIZE=$5

if [ -z $OUTDIR ]; then
  OUTDIR=.
fi

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

if [ -z $WINSIZE ]; then
  WINSIZE=5000
fi

# check if file exists
if [[ ! -f $INPUT ]]; then >&2 echo "file \"$INPUT\" not found"; exit 1; fi
if [[ ! -f $CHROMSIZE ]]; then >&2 echo "file \"$CHROMSIZE\" not found"; exit 1; fi

# output file name
BASE=$OUTDIR/$OUTPREFIX
OUTPUT=${BASE}.w${WINSIZE}.bedGraph
BINFILE=${BASE}.w${WINSIZE}.bin
COVERAGEFILE=${BASE}.w${WINSIZE}.cov
FULLCHRSIZE=${BASE}.full.chrsize

# determine scale
SCALE=$(echo "1000000/$(samtools view -c $INPUT)" | bc -l)

# get full chromsize from ban header
samtools view -H $INPUT | bamH2chrsize > $FULLCHRSIZE

# run count command
bedtools makewindows -w $WINSIZE -g $FULLCHRSIZE > $BINFILE
 
# get full coverage file 
bedtools coverage -counts -sorted -a $BINFILE -b $INPUT > $COVERAGEFILE

# filter coverage by input chromsize
filtercov $COVERAGEFILE $CHROMSIZE > $COVERAGEFILE.filtered

awk -v scale=$SCALE '{print $1,$2,$3,$4*1000*(scale/($3-$2)) }' OFS='\t' $COVERAGEFILE.filtered > $OUTPUT
bgzip $OUTPUT
