#!/usr/bin/env bash
INPUT=$1
OUTPREFIX=$2
WINSIZE=$3
MINSIZE=$4

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

if [ -z $WINSIZE ]; then
  WINSIZE=5000
fi

if [ -z $MINSIZE ]; then
  MINSIZE=10000000
fi

# check if file exists
if [[ ! -f $INPUT ]]; then >&2 echo "file \"$INPUT\" not found"; exit 1; fi
  
BASE=$OUTPREFIX
OUTPUT=${BASE}_w${WINSIZE}.bg
  
SCALE=$(echo "1000000/$(samtools view -c $INPUT)" | bc -l)
  
samtools view -H $INPUT | grep "^@SQ" | tr ':' '\t' | cut -f 3,5 | \
awk -v minsize=$MINSIZE '$2>minsize' OFS='\t' | \
bedtools makewindows -w $WINSIZE -g /dev/stdin | \
bedtools coverage -counts -sorted -c -a stdin -b $INPUT | \
awk -v scale=$SCALE '{print $1,$2,$3,$4*1000*(scale/($3-$2)) }' OFS='\t' > $OUTPUT
