#!/usr/bin/env bash
INPUT=$1
OUTPREFIX=$2
  
# check if file exists
if [[ ! -f $INPUT ]]; then echo "file \"$INPUT\" not found"; exit 1; fi
  
UCOUNT=$(samtools view $INPUT | cut -f 1 | head -n 1000 | sort | uniq | wc -l)
  
if [[ UCOUNT -lt 1000 ]]; then
  PAIRARG=""
else
  PAIRARG="-s"
fi 
  
BASE=$OUTPREFIX
OUTPUT=${BASE}_rmdup.bam
LOGFILE=${BASE}_rmdup.bam.log
  
samtools rmdup $PAIRARG $INPUT $OUTPUT 2> $LOGFILE
