#!/usr/bin/env bash

INPUT=$1
MEMPERTHREAD=$2  # default "5G"
outdir=$3  # default "."
outprefix=$4  # default "out"

if [ -z $MEMPERTHREAD ]; then
  MEMPERTHREAD=5G
fi

if [ -z $outdir ]; then
  outdir=.
fi

if [ -z $outprefix ]; then
  outprefix=out
fi

BASE=$outdir/outprefix
OUTPUT=${BASE}.q20_sort.bam
samtools view -bq 20 $INPUT | samtools sort -m $MEMPERTHREAD - > $OUTPUT

