#!/usr/bin/env bash
INPUT=$1  # .bg
OUTDIR=$2  # default "."
OUTPREFIX=$3  # default "out"
MINRPKM=$4  # default 0.1

# default options
if [ -z $OUTDIR ]; then
  OUTDIR=.
fi

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

if [ -z $MINRPKM ]; then
  MINRPKM=0.1
fi

# check input file
if [[ ! -f $INPUT ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi


paste $INPUT | awk -v minrpkm=$MINRPKM \
  '{for(i=4;i<=NF;i+=4){scoresum+=$i}; if((scoresum/(NF/4))>=minrpkm){print $1,$2,$3};scoresum=0}' \
OFS='\t' > filtered.bed

BG=$INPUT
FW=filtered.bed
  
BASE=$OUTDIR/$OUTPREFIX
OUTPUT="${BASE}.filtered.bg"
  
bedtools intersect -sorted -u -a $BG -b $FW > $OUTPUT
 
