#!/usr/bin/env bash
INPUT=$1  # .bg
OUTPREFIX=$2
MINRPKM=$3

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

if [ -z $MINRPKM ]; then
  MINRPKM=0.1
fi

if [[ ! -f $INPUT ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi

paste $INPUT | awk -v minrpkm=$MINRPKM \
  '{for(i=4;i<=NF;i+=4){scoresum+=$i}; if((scoresum/(NF/4))>=minrpkm){print $1,$2,$3};scoresum=0}' \
OFS='\t' > filtered.bed

BG=$INPUT
FW=filtered.bed
  
BASE=$OUTPREFIX
OUTPUT="${BASE}_filtered.bg"
  
bedtools intersect -sorted -u -a $BG -b $FW > $OUTPUT
 
