#!/usr/bin/env bash
EBG=$1
LBG=$2
OUTPREFIX=$3

# check if file exists
if [[ ! -f $EBG ]]; then echo "file \"$EBG\" not found"; exit 1; fi
if [[ ! -f $LBG ]]; then echo "file \"$LBG\" not found"; exit 1; fi

# check input is a fastq
if [[ $EBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi
if [[ $LBG != *.bg ]]; then echo "input is not a bedGraph file"; exit 1; fi

EMIN=$(cut -f 4 $EBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)
LMIN=$(cut -f 4 $LBG | sort | uniq -c | awk '{print $2-a;a=$2}' | sort | uniq -c | awk '{print $1,$2}' | sort -k1,1nr | head -n 1 | cut -d' ' -f 2)


OUTPUT=$OUTPREFIX.l2r.out  ## is this bg?
LOGFILE=${OUTPUT}.log

paste $EBG $LBG | awk -v emin=$EMIN -v lmin=$LMIN '{print $1,$2,$3,log(($4+emin)/($8+lmin))/log(2)}' OFS='\t' > $OUTPUT

