#!/usr/bin/env bash
# usage : outdir outprefix nthreads inputbg1 inputbg2 inputbg3 ...
OUTDIR=$1  # eg "."
OUTPREFIX=$2  # eg "out"
NTHREADS=$3
shift
shift
shift

INFILESTR=${@}
INFILES=(${INFILESTR// / })
NFILES=${#INFILES[@]}


# check input file exists
if [[ ! -f $INPUT ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi

# default options
if [ -z $OUTDIR ]; then
  OUTDIR=.
fi

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

BASE=$OUTDIR/$OUTPREFIX
OUTPUTALL="${BASE}.inorm.bg"

iqrn(){
  BG=$1
  OUTPUT="$(mktemp).bg"
  
  NUMLINES=$(cat $BG | wc -l)
  Q1=$(echo $NUMLINES/4 | bc)
  Q2=$(echo $NUMLINES/2 | bc)
  Q3=$(echo 3*$NUMLINES/4 | bc)
  ST=$(sort -k4,4n $BG | \
    awk -v q1=$Q1 -v q2=$Q2 -v q3=$Q3 '{if(NR==q1){Q1=$4};if(NR==q2){Q2=$4};if(NR==q3){Q3=$4}}END{print Q3-Q1,Q2}')
  REFIQR=5.5
  IQR=$(echo $ST | cut -d ' ' -f 1)
  MDN=$(echo $ST | cut -d ' ' -f 2)
  awk -v refiqr=$REFIQR -v mdn=$MDN -v iqr=$IQR 'BEGIN{scalar=refiqr/iqr} {print $1,$2,$3,($4-mdn)*scalar}' OFS='\t' $BG > $OUTPUT
  echo $OUTPUT
}

INPUTI=$(parallel --no-notice -k -j $NTHREADS "iqrn {}" ::: $INFILESTR)
cat $INPUTI > $OUTPUTALL
