#!/usr/bin/env bash
INPUT=$1
OUTPREFIX=$2  # optional
REFERENCE=$3  # optional

if [ -z $OUTPREFIX ]; then
  OUTPREFIX=out
fi

for i in $INPUT; do
  if [[ ! -f $i ]]; then >&2 echo "file \"$i\" not found"; exit 1; fi
done

iqrn(){
  BG=$1
  BASE=$OUTPREFIX
  OUTPUT="${BASE}_inorm.bg"
  
  NUMLINES=$(cat $BG | wc -l)
  Q1=$(echo $NUMLINES/4 | bc)
  Q2=$(echo $NUMLINES/2 | bc)
  Q3=$(echo 3*$NUMLINES/4 | bc)
  ST=$(sort -k4,4n $BG | \
    awk -v q1=$Q1 -v q2=$Q2 -v q3=$Q3 '{if(NR==q1){Q1=$4};if(NR==q2){Q2=$4};if(NR==q3){Q3=$4}}END{print Q3-Q1,Q2}')
  REFIQR=5.5
  IQR=$(echo $ST | cut -d ' ' -f 1)
  MDN=$(echo $ST | cut -d ' ' -f 2)
  awk -v refiqr=$REFIQR -v mdn=$MDN -v iqr=$IQR 'BEGIN{scalar=refiqr/iqr} {print $1,$2,$3,($4-mdn)*scalar}' OFS='\t' $BG > $OUTPUT
  echo $OUTPUT
}

normalize(){
  BG=$1
  RF=$2
  
  BASE=$OUTPREFIX
  OUTPUT="${BASE}_qnorm.bg"
  BGLINES=$(cat $BG | wc -l)
  RFLINES=$(cat $RF | wc -l)
  TMPREFN="$(mktemp).bg"
  
  if [[ $BGLINES -gt $RFLINES ]]; then
    COPYNUM=$((1+BGLINES/RFLINES))
    cat $(yes "$RF" | head -n $COPYNUM) > $TMPREFN
    RF=$TMPREFN
  fi
  
  paste <(sort -T . -k4,4g $BG) <(shuf -n $BGLINES $RF | sort -k4,4g) | \
    cut -f 1,2,3,8 | sort -k1,1 -k2,2n > $OUTPUT
  
  rm -f $TMPREFN
  
  echo $OUTPUT
}

if [[ ! -f $REFERENCE ]]; then
  >&2 echo "reference file not found, making an average distribution"
  INPUTI=$(iqrn $INPUT)
  tmprefi="$(mktemp).bg"
  cat $INPUTI > $tmprefi
  REFERENCE=$tmprefi
else
  if [[ $REFERENCE != *.bg ]]; then
    >&2 echo "file \"$REFERENCE\" is not a bedGraph file"
    exit 1
  fi
fi

normalize $INPUT $REFERENCE

rm -f tmprefi
